type=javaprocess
java.class=com.haima.sage.bigdata.azkaban.Application
failure.emails=bigdata@haima.me
classpath=/data/service/azkaban-3.38.0/azkaban-exec-server-0.1.0-SNAPSHOT/lib/sage-bigdata-azkaban-framework.jar
main.args=takeout report_export_tbl_ex_statistics_warn.sh ${azkaban.flow.start.year}-${azkaban.flow.start.month}-${azkaban.flow.start.day} ${azkaban.flow.start.hour}
dependencies=report_export_comment_detail