type=javaprocess
java.class=com.haima.sage.bigdata.azkaban.Application
failure.emails=deepinsight@haima.me
classpath=/data/service/azkaban-3.38.0/azkaban-exec-server-0.1.0-SNAPSHOT/lib/sage-bigdata-azkaban-framework.jar
main.args=bigdata/douyin/advert advert_douyin_industrybrand_personas_area_es.sh ${azkaban.flow.start.year}-${azkaban.flow.start.month}-${azkaban.flow.start.day} ${azkaban.flow.start.hour}
dependencies=douyin_advert_source_keywords_data,douyin_advert_pbrand_brand_dat