type=javaprocess
java.class=com.haima.sage.bigdata.azkaban.Application
failure.emails=deepinsight@haima.me
classpath=/data/service/azkaban-3.38.0/azkaban-exec-server-0.1.0-SNAPSHOT/lib/sage-bigdata-azkaban-framework.jar
main.args=bigdata/douyin/advert advert_douyin_content_calc_es.sh ${azkaban.flow.start.year}-${azkaban.flow.start.month}-${azkaban.flow.start.day} ${azkaban.flow.start.hour}
dependencies=douyin_advert_source_keywords_data,douyin_advert_content_calc_data,douyin_advert_kol_property_brand_industry,advert_douyin_kol_mark_daily_snapshot