type=javaprocess
java.class=com.haima.sage.bigdata.azkaban.Application
failure.emails=deepinsight@haima.me
classpath=/data/service/azkaban-3.38.0/azkaban-exec-server-0.1.0-SNAPSHOT/lib/sage-bigdata-azkaban-framework.jar
main.args=bigdata/douyin/advert douyin_advert_source_keywords_data.sh ${azkaban.flow.start.year}-${azkaban.flow.start.month}-${azkaban.flow.start.day} ${azkaban.flow.start.hour}
dependencies=douyin_advert_brand_keywords_snapshot,douyin_advert_categroy_keywords_snapshot