type=javaprocess
java.class=com.haima.sage.bigdata.azkaban.Application
failure.emails=deepinsight@haima.me
classpath=/data/service/azkaban-3.38.0/azkaban-exec-server-0.1.0-SNAPSHOT/lib/sage-bigdata-azkaban-framework.jar
main.args=bigdata/huya/finance data_import_huya_live_new_user_info_snapshot.sh ${azkaban.flow.start.year}-${azkaban.flow.start.month}-${azkaban.flow.start.day} ${azkaban.flow.start.hour}
dependencies=data_import_huya_live_all_user_info_snapshot