type=javaprocess
java.class=com.haima.sage.bigdata.azkaban.Application
failure.emails=renguangtao@haima.me
classpath=/data/service/azkaban-3.38.0/azkaban-exec-server-0.1.0-SNAPSHOT/lib/sage-bigdata-azkaban-framework.jar
main.args=bigdata/meituan meituan_produce_hive_es.sh ${azkaban.flow.start.year}-${azkaban.flow.start.month}-${azkaban.flow.start.day} ${azkaban.flow.start.hour}
dependencies=meituan_produce_hive_result_table