type=javaprocess
java.class=com.haima.sage.bigdata.azkaban.Application
failure.emails=zhaowang@haima.me
classpath=/data/service/azkaban-3.38.0/azkaban-exec-server-0.1.0-SNAPSHOT/lib/sage-bigdata-azkaban-framework.jar
main.args=bigdata/boyu_jd 2_boyu_jd_goods_mix_snapshot.sh ${azkaban.flow.start.year}-${azkaban.flow.start.month}-${azkaban.flow.start.day} ${azkaban.flow.start.hour}
dependencies=01.boyu_jd_goods_day_snapshot