type=javaprocess
java.class=com.haima.sage.bigdata.azkaban.Application
failure.emails=ningguanyi@haima.me
classpath=/data/service/azkaban-3.38.0/azkaban-exec-server-0.1.0-SNAPSHOT/lib/sage-bigdata-azkaban-framework.jar
main.args=bigdata/uxin uxin_car_info_new_snapshot_blood.sh ${azkaban.flow.start.year}-${azkaban.flow.start.month}-${azkaban.flow.start.day} ${azkaban.flow.start.hour}
dependencies=uxin_car_price_analysis_snapshot_blood