type=javaprocess
java.class=com.haima.sage.bigdata.azkaban.Application
failure.emails=liguangbao@haima.me
classpath=/data/service/azkaban-3.38.0/azkaban-exec-server-0.1.0-SNAPSHOT/lib/sage-bigdata-azkaban-framework.jar
main.args=bigdata/bili 03.bili_live_user_info_snapshot.sh ${azkaban.flow.start.year}-${azkaban.flow.start.month}-${azkaban.flow.start.day} ${azkaban.flow.start.hour}
dependencies=bili_live_temporary_tables_snapshot